---
name: pr

on:
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]

    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}

      - name: Test
        run: mvn --no-transfer-progress test
